### ISSUE TITLE
Code using qrs-interact throws warnings in debug mode

### ISSUE THREAD

**Issue by goldbergjeffrey** [jparis/qrs-interact#20] opened 2016-07-26 16:10 UTC
Message from console: Warning: a promise was created in a handler but was not returned from it.

From research indicates runaway promises that don't return a value.

**Comment by jparis** [comment] 2016-09-28 19:41
Do you still get this? Can't reproduce in my tests.

**Comment by jparis** [comment] 2016-09-28 22:45
Cannot reproduce, closing this issue.

**Closed as completed by jparis** 2016-09-28 22:45 UTC
Labels: bug
